[project]
name = "agent-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openai-agents>=0.5.1",
    "python-dotenv>=1.2.1",
    "streamlit>=1.50.0",
    "supabase>=2.0.0",
]
